-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 19:45:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema it_soluctions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it_soluctions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it_soluctions` DEFAULT CHARACTER SET utf8 ;
USE `it_soluctions` ;

-- -----------------------------------------------------
-- Table `it_soluctions`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Cargos` (
  `idCargos` INT NOT NULL AUTO_INCREMENT,
  `nomeCargo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Enderecos` (
  `idEnderecos` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnderecos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Equipes` (
  `idEquipes` INT NOT NULL AUTO_INCREMENT,
  `nomeEquipe` VARCHAR(255) NOT NULL,
  `numeroRecursos` INT NOT NULL,
  PRIMARY KEY (`idEquipes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Recursos` (
  `idRecursos` INT NOT NULL AUTO_INCREMENT,
  `nomeRecurso` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  `Cargos_idCargos` INT NOT NULL,
  `Enderecos_idEnderecos` INT NOT NULL,
  `Equipes_idEquipes` INT NOT NULL,
  PRIMARY KEY (`idRecursos`),
  INDEX `fk_Recursos_Cargos1_idx` (`Cargos_idCargos` ASC) VISIBLE,
  INDEX `fk_Recursos_Enderecos1_idx` (`Enderecos_idEnderecos` ASC) VISIBLE,
  INDEX `fk_Recursos_Equipes1_idx` (`Equipes_idEquipes` ASC) VISIBLE,
  CONSTRAINT `fk_Recursos_Cargos1`
    FOREIGN KEY (`Cargos_idCargos`)
    REFERENCES `it_soluctions`.`Cargos` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_Enderecos1`
    FOREIGN KEY (`Enderecos_idEnderecos`)
    REFERENCES `it_soluctions`.`Enderecos` (`idEnderecos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_Equipes1`
    FOREIGN KEY (`Equipes_idEquipes`)
    REFERENCES `it_soluctions`.`Equipes` (`idEquipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `tipoTelefone` VARCHAR(45) NOT NULL,
  `numeroTelefone` VARCHAR(45) NOT NULL,
  `Recursos_idRecursos` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Contatos_Recursos1_idx` (`Recursos_idRecursos` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Recursos1`
    FOREIGN KEY (`Recursos_idRecursos`)
    REFERENCES `it_soluctions`.`Recursos` (`idRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Ferramentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Ferramentas` (
  `idFerramentas` INT NOT NULL AUTO_INCREMENT,
  `nomeFerramenta` VARCHAR(255) NOT NULL,
  `versao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFerramentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`FerramentasRecursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`FerramentasRecursos` (
  `idFerramentasRecursos` INT NOT NULL AUTO_INCREMENT,
  `Recursos_idRecursos` INT NOT NULL,
  `Ferramentas_idFerramentas` INT NOT NULL,
  INDEX `fk_Recursos_has_Ferramentas_Ferramentas1_idx` (`Ferramentas_idFerramentas` ASC) VISIBLE,
  INDEX `fk_Recursos_has_Ferramentas_Recursos1_idx` (`Recursos_idRecursos` ASC) VISIBLE,
  PRIMARY KEY (`idFerramentasRecursos`),
  CONSTRAINT `fk_Recursos_has_Ferramentas_Recursos1`
    FOREIGN KEY (`Recursos_idRecursos`)
    REFERENCES `it_soluctions`.`Recursos` (`idRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_has_Ferramentas_Ferramentas1`
    FOREIGN KEY (`Ferramentas_idFerramentas`)
    REFERENCES `it_soluctions`.`Ferramentas` (`idFerramentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Projetos` (
  `idProjetos` INT NOT NULL AUTO_INCREMENT,
  `nomeProjeto` VARCHAR(255) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataPrevisaoTermino` DATE NOT NULL,
  `dataTermino` DATE NULL,
  `status` ENUM("Em aberto", "Em andamento", "Concluido") NOT NULL,
  `horasPrevistas` DOUBLE NOT NULL,
  `horasUtilizadas` DOUBLE NULL,
  `Equipes_idEquipes` INT NOT NULL,
  `Recursos_idGerente` INT NOT NULL,
  PRIMARY KEY (`idProjetos`),
  INDEX `fk_Projetos_Equipes1_idx` (`Equipes_idEquipes` ASC) VISIBLE,
  INDEX `fk_Projetos_Recursos1_idx` (`Recursos_idGerente` ASC) VISIBLE,
  CONSTRAINT `fk_Projetos_Equipes1`
    FOREIGN KEY (`Equipes_idEquipes`)
    REFERENCES `it_soluctions`.`Equipes` (`idEquipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projetos_Recursos1`
    FOREIGN KEY (`Recursos_idGerente`)
    REFERENCES `it_soluctions`.`Recursos` (`idRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Atividades` (
  `idAtividades` INT NOT NULL AUTO_INCREMENT,
  `nomeAtividade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAtividades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`ProjetosAtividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`ProjetosAtividades` (
  `idProjetosAtividades` INT NOT NULL AUTO_INCREMENT,
  `Projetos_idProjetos` INT NOT NULL,
  `Atividades_idAtividades` INT NOT NULL,
  PRIMARY KEY (`idProjetosAtividades`),
  INDEX `fk_Projetos_has_Atividades_Atividades1_idx` (`Atividades_idAtividades` ASC) VISIBLE,
  INDEX `fk_Projetos_has_Atividades_Projetos1_idx` (`Projetos_idProjetos` ASC) VISIBLE,
  CONSTRAINT `fk_Projetos_has_Atividades_Projetos1`
    FOREIGN KEY (`Projetos_idProjetos`)
    REFERENCES `it_soluctions`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projetos_has_Atividades_Atividades1`
    FOREIGN KEY (`Atividades_idAtividades`)
    REFERENCES `it_soluctions`.`Atividades` (`idAtividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`Tarefas` (
  `idTarefas` INT NOT NULL AUTO_INCREMENT,
  `descricaoTarefa` TEXT NOT NULL,
  `Atividades_idAtividades` INT NOT NULL,
  PRIMARY KEY (`idTarefas`),
  INDEX `fk_Tarefas_Atividades1_idx` (`Atividades_idAtividades` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefas_Atividades1`
    FOREIGN KEY (`Atividades_idAtividades`)
    REFERENCES `it_soluctions`.`Atividades` (`idAtividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_soluctions`.`HistoricoSalario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_soluctions`.`HistoricoSalario` (
  `idHistoricoSalario` INT NOT NULL AUTO_INCREMENT,
  `dataAumento` DATE NULL,
  `valorAumento` FLOAT NULL,
  `Recursos_idRecursos` INT NOT NULL,
  PRIMARY KEY (`idHistoricoSalario`),
  INDEX `fk_HistoricoSalario_Recursos1_idx` (`Recursos_idRecursos` ASC) VISIBLE,
  CONSTRAINT `fk_HistoricoSalario_Recursos1`
    FOREIGN KEY (`Recursos_idRecursos`)
    REFERENCES `it_soluctions`.`Recursos` (`idRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
